version: '3'

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./storage/logs/nginx:/var/log/nginx
    ports:
      - 8080:80
    links:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=app
      - DB_USERNAME=app
      - DB_PASSWORD=app
    volumes:
      - ./:/var/www
    links:
      - mysql


  php-cli:
    build:
      context: docker/php-cli
      dockerfile: Dockerfile
    environment:
    - DB_CONNECTION=mysql
    - DB_HOST=mysql
    - DB_PORT=3306
    - DB_DATABASE=app
    - DB_USERNAME=app
    - DB_PASSWORD=app
    volumes:
    - ./:/var/www
    links:
    - mysql
    tty: true

  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=app
    ports:
      - 33061:3306

# Storages
volumes:
  database:
    driver: local